name: Build Docker Images & Push To ECR

on:
  push:
    branches:
      - build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.event.head_commit.message }}
    - name: Pushing docker to ECR
      run: docker push ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.event.head_commit.message }}